language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env:
        - COMPILER=g++-5

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env:
        - COMPILER=g++-6


before_script:
  - sudo add-apt-repository --yes ppa:samuel-bachmann/boost
  - sudo apt-get update

script: mkdir build && cd build && cmake .. -G "Unix Makefiles"  && make CXX=$COMPILER -j3 VERBOSE=1 && cd ..


